FROM stevenfollis/oneapi:hpc-toolkit-2024.2.1
#FROM stevenfollis/intel-containers:intel-gpu-lts

# Copy Jupyter notebook and supporting files into container image
COPY --chown=jovyan:100 . /home/jovyan/