FROM stevenfollis/oneapi:hpc-toolkit-2024.2.1

# COPY --chown=jovyan:users GettingStartedHPCToolkit.ipynb /home/jovyan/catalog/sample/
# COPY --chown=jovyan:users matrix_mul/ /home/jovyan/catalog/sample/matrix_mul/
WORKDIR /home/jovyan/catalog/sample/
COPY . .