# Hadoline Configuration File
# Used to lint Dockerifle
# https://github.com/hadolint/hadolint?tab=readme-ov-file#configure

no-fail: true
format: tty
ignored:
  - DL3008 # https://github.com/hadolint/hadolint/wiki/DL3008
