name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - oneapi/base-toolkit/**
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file /oneapi/base-toolkit/Dockerfile --tag stevenfollis/oneapi:base-toolkit-{{ github.head_ref }}.${{ github.sha }}
